language: python
python:
- '3.6'
- 3.7-dev
install:
- pip install tox-travis codecov flit
script:
- tox
before_deploy: flit build
deploy:
  skip_cleanup: true
  provider: pypi
  user: anthonypjshaw
  password:
    secure: "PWSCCkV71pK/jTadoNOFyLYuWt24qQulOhd+2KBZUBYtdBbjrWFNM9wfCX949W0ipKDtkeDUcnaMISuKdzttu0IF6gYozov4PrPdWCkyj5BBj+GL5ZimkYvGGn+Ffj5NtAiW01+QR3HcwnjLEI7fJ2FAxTxYTc/eu9/DciH/pYVMFZMSP2cFD8EnN/zIE8wdn5SEdot91dy5GfBaBJy/TJkiSOcJ8cCeF0P6atS2vpvllPyCinKe3w/pIvD4bUASrAX7F6ldGfTygTt7cEd4jsqNWEjA529stAJs9WrEt87TFCVK7tupRrOQWaovrkX7NeatdA2CyGOrpUAdhBcuyIeP5j0G2EH7NgumUOQLebC2o7JJKfTEi/qmjYcZXuDP9x/4MQm/PqTZNFAk+ecevvISy1zQck/pctyvzor/vlfFn0Ze2R+QGq6kgsOe7ff6aDPAysINS2ElPIe1A16lEKNZKwZdwVBuS22HAYzYUhJA4iI1dNDBIR433/PyzcuccgVXFgChxu6Ja0uAPc8iaJq+uDfoE5WbAKp+DLDVpkQ/WVUglM5QdT1HfjO/1rRvMkBRM3YUEVqK38UbEFQmuKmKkoPn+Xscs8BN7hf5BYFgjSUP6DyF41sBBHhLGuQJninsDP76GRNdUYodIendSt+NqNpeygo+HIYlBVmznSs="