language: python
python:
- '3.6'
- 3.7-dev
stages:
- name: after_script
  if: branch = master
install:
- pip install tox-travis codecov flit
script:
- tox
after_script:
- flit build
- flit publish
env:
  global:
  - secure: jac4EAZaoLM4g6Ljd+jgukox6E02ADjNNGqcjp05aV+qoDKFygsoMpefTiTjrsGfb/s4AJoLWs+Q6aLSA3V1z6L0TFZcvCQ0dWu+gvq3vq+ChwL5hmAXVhpPL739/TzgfBEN/f4uon8OD2hPWuIa+upK0iFHWjoIYMrfwcPQsFb+YzHxRcIAXezai9IcCU4VHDfi7+Oh61VpY4Iu4lH9a3+ngncE+d+vn0JtRccVn8UEDp8EdQ6i4gTjSqT2NNq6PrDu5lK1uc3oP94FlE/82hAZkBLl109tY4KFKzJ7NPYaB6kIxGh6GZfUyHtrO/A7zzc9K5CniIjwtibr1vIE3uAn1rY2RPWywWW/5C2nXhUAYpiBkt5AdLts1T7uJYOkkHtgDAPovCL3y7xj88RIFpD3Lcu0ITtYS9IoPtJ5mKVlShQDVYTP7yzZ4LrEuVVbJJuJ9NERWMLDrPTb/if3tl8u4cHHGM3Ps6dabwJYaGEyTGCxPDVFL0u/9U6hasNfJGqri1ajkrKjIZ40WIEv6hXKwXK5aF7RuwrWLHqkdA0eCyc6Gjvu5JD4wMJ5tLDXH5wu0GrqRryiLQjbn8eka/QsTP+FHYzrcAU6Yy5LepCEL6f/Bxv/Qqzm9htOmrr1WNQfi9nZqNME+PPW9KWGHKPQ5idBFGZBMaQDkngditA=
  - secure: GpsVGF18G/I2SWlSq39VecB2jt6NSNFVCaxNNPf0Rs6riArup7APbS9XyzVbFyb+T7gcAo8GKM82UMANHGaRoZbUE5qXxPpS+miC+Aj3LhCExdO/cwL6uRPt1z3MXxc5WHyRxpJZmwpe8m4ZDwzmWSK74bVAf/uPDNsIaj5WsT2k/U5QagevTIq3mvovCC1ubRPM40t5nzfzlHfiNPRjylVSRNdU0z++2vXTWPTVp9ottlwRx+9S3Mkr7LobIEZBkMmGCoHnonvOHxijQstSJouImNMkOzIxA9OUludmjESqCUdst5Jdp0/5gX14kFoLlzZCRWkP8xCUZzwXrlykD+H+kiryWi/drEQljF3LRU1AOA2W15GNMZxExEGX1lnIO/6s114A9zdJdJWyCvXRszibcaSMWV6HJibG0rwZdtdX0IEczLXchCZX9i3Fx2/N0cfMEBfsja482fuNeb4yfCohS2NXxCyHZIqxif0avRuynlQ4637TP9eJGVLMXvppzkTZIHd7LHOpuF7Q5qjeYvN6/MBV4NFDBIW4vDBmdkq6j/9eOBAblNukEtUo/yP6B9b5bG5tGf4FiueWxYndry6wAWlh669DYg4GzHa6sRE/PJll02l/scK5PIl5r6MkeGrdydPYZdZMPNkGUyE65NPBZoYgZCEHJLbJklMMtJ8=
