language: python
python:
- '3.6'
- 3.7-dev
stages:
- name: after_script
  if: branch = master
install:
- pip install tox-travis codecov flit
script:
- tox
after_script:
- flit build
- flit publish


env:
  global:
  - secure: Mnzj6UetK2HY5pcXlCxR4PMkhahg0fjAcPdDYu9uHg3U0PAvqtvKo5yQNiLkvWaR0fO6603eifGes0ix9DhU7hQaECF5Ap55iySr93AnZ/DfZfncDVr4XWuLu+TvyvIp7I/yKrGYn0Ngf4Y775TMIEOFZnvUnITDQSZ0amztdzUs/sUxDY2+kHKvDAxXnVSOAwsJdM6Om7y9HMXeFBVhS2U3PHds4ODh6ZQdB17I3vSrbZg7Bzz5I8GRyBSl4pXA+F0jtnul9rBnTEYMUGiBaIcc7IYHiSkY1mP+6go4xu4YvQ3rPue9y8DSKJnWJtwJB901ZfG8zRn83Fmb9XE72X331in44vDbSoApHGV3Ftsz3xrihMuMsIel9IPMSmdl60HaEahwcxSDc0NfWIepzzK5LQC+P7uU8VpTWCoH9mVegFvtzu2VwUwS8YmTwmxRREOvJvhp153p/47I5V/Q7QflYijrFrGM+Bwexwr7VATdslOc+ujurnmUH1kPZopKNiFJ3/9ZiiWqhCUtBtrY2ltKUAhenBgwYQL8+tiIHWZvwEBSZX3r9K8UouTCPvBTgaqMwTJkOOrv1LU3T656jy8BCFGcwkNBNzinz0Y/Vskd6roJqUYSi3C/t93N0cpVd+6XnhRtCY7cLS4DOQvwYAq1lFlgyGCg/Y0Rkt+jfK4=
  - secure: heqYF4Ng+tTtbTRNwt314MKeN/MTSPFzQA+lF6QnAmWvpIlzBcrhBtFKGrxgWtX9OxnD6F1pSaAhyVaBonbjJEHdOKIxeRV1ULYt5HY09v8RAexieo01U3EtZj6LdRXPpW5fKHb237fKnUWIZ+zQmaWHqMp+znNgWpmTCxf7xsCkJmOgV0v9sI4OlEhJ64UlSiKqqH2Jg6TucRL2kVnF95W8+i+HohRriznbuuIutux8MarZ4bN1H2LRigdtFhyyTBsMlDlC5aDqi55Lu6fgDU64Jodrot2su7m7+5GWl6ZtQEuMdzJi97zX2SiYeAoTG9oKPNZw7yHEMqafTqTl7BS+X4qR5p0XJnMdh8Dm3N81KpWIrHlV8MX4EHLGc7iDpaG9qo6Yp6wxquuNMwagwd7gdqclkmuKfAI/OuowOdYjwdAniCnsq9JxL64i7qDDCxsrq5dAzjorsco/pFlr75fSwdKmmdaNUS3MBO79DS8KQTu7/doDvJWoXpNpiYVfSYPBsMli7GyRBHL10za08iOoiOiedjEdGAoMBWzEcomJCc0BSW2urAFqpg7Y2tlb/Wb3JbwpgMNxusJBBSZMxVzAEQl8cEdHcFegKmAQyVDdr6Eyo//9aMfLTGKDpb8t6Ai95jatReT8FqxRkdey99zcVK9rRHX9/NCR0qWuAhs=
