[build-system]
requires = [
    "flit",
    "gitpython",
    "radon",
    "click",
    "colorlog",
    "tabulate",
    "dataclasses; python_version == '3.6'",]
build-backend = "flit.buildapi"
requires-python = ">=3.6"
description-file = "README.md"

[tool.flit.metadata]
module = "wily"
author = "Anthony Shaw"
author-email = "anthonyshaw@apache.org"
home-page = "https://github.com/tonybaloney/wily"
classifiers = ["License :: OSI Approved :: Apache Software License"]

[tool.flit.scripts]
wily = "wily:cli"